# Site Settings
title: Pill Popper
email: apremrenu@gmail.com
description: >
  An Automated, Controlled and Secured Pill Dispenser
baseurl: ""
url: "www.contrib.andrew.cmu.edu/~apremren"
twitter_username: taniarascia
github_username:  aishprr
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM